# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9e723bad8327992ae43d11c87cde25709da80b63405e484ea3f9de692d6803b1ef85d287335dbb970b82ecba7830a326e686330a9ea6bc2b3a4679ce25c97ba

test:
  secret_key_base: d98dfa309f53f60861874087eaedd352a62827ca5a22dc4f7d32beadc21bcb0a0f1beb8f9fdb0d947c19059e3b5a89333ab84285df6b7010796d023809b8cc16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
